<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Lenovo-PC" failures="1" tests="7" name="Test" time="13.25" errors="0" timestamp="2024-02-06T11:40:12 IST">
  <testcase classname="apiframework.CreateCustomerTest" name="validateCreateCustomerAPIWithInValidSecretKey" time="4.563"/>
  <testcase classname="apiframework.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="1.934"/>
  <testcase classname="apiframework.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="0.603"/>
  <testcase classname="apiframework.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="0.878"/>
  <testcase classname="apiframework.CreateCustomerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="0.799"/>
  <testcase classname="apiframework.DeleteCustomerTest" name="deleteCustomerWithValidID" time="0.527"/>
  <testcase classname="apiframework.DeleteCustomerTest" name="deleteCustomerWithValidIDWithDeletedRecord" time="0.411">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at apiframework.DeleteCustomerTest.deleteCustomerWithValidIDWithDeletedRecord(DeleteCustomerTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomerWithValidIDWithDeletedRecord -->
  <testcase classname="apiframework.BaseTest" name="@AfterTest tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="apiframework.BaseTest" name="@BeforeTest setUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUp -->
</testsuite> <!-- Test -->
